[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
# Упрощаем правила до базовых ошибок синтаксиса/логики (E,F), чтобы не мешать защите
select = ["E", "F"]
ignore = ["E203", "E501"]
exclude = [
  ".venv",
  "models",
  "data_dw",
  "data_raw",
  "__pycache__",
  "backup_models_*",
  "experiments",
  "notebooks",
  "docs",
]

[tool.ruff.isort]
combine-as-imports = true

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = false
no_implicit_optional = true
check_untyped_defs = true
exclude = '(^models/|^data_dw/|^data_raw/|^__pycache__/|^\.venv/)'
